### ISSUE TITLE
setLocale() or context.locale=Locale("...") is not Updating app locale instantly

### ISSUE THREAD

**Issue by red-star25** [aissat/easy_localization#370]
I've updated easy_localization: 3.0.0 package from easy_localization: ^2.3.3.
When i was using easy_localization: ^2.3.3 it is updating my app locale instantly whenever i called 
```
setState(() {
   context.locale = Locale("en");
});
```

But since I've updated the package version to 3.0.0 it is not updating the locale instantly. I've to hot restart  the whole app to see the changes.

Here is what im doing in version 3.0.0

`onTap: () async {
         await homeController
                        .setLanguage("EN")
                            .then((value) async {
                                 await context
                                  .setLocale(
                                    const Locale( "en"));
                                     })
},`

And here is what im doing in version 2.3.3 (which is working,and updating locale instantly)
`onTap: () {
                                                        homeController
                                                            .setLanguage("EN");
                                                        setState(() {
                                                          context.locale =
                                                              const Locale(
                                                                  "en");
                                                        });
                                                      },`

**Comment by xbasic** [comment]
I have the same regression on my app too. The local has been changed, but there is now refresh. Is this a breaking change and how can I force a refresh on locale change if so ?

**Comment by SalehHub** [comment]
For me the app text direction changes based on the new language(rtl) but the new languages' keys doesn't load and UI not updating. 
No error messages

**Comment by armandojimenez** [comment]
Same thing happening on my app

**Comment by Fethi-Hamdani** [comment]
same issue here

**Comment by Pilaba** [comment]
same energy on my end

**Comment by Overman775** [comment]
Thanks for issue, i will check

**Comment by AhmedAbouelkher** [comment]
I have the same problem with `easy_localization: ^3.0.0` with Arabic and English, when changing the current locale the direction changes but the actual localized titles don't.

**Comment by OmniaMahmoud** [comment]
the same issue in my app.
any updates?

**Comment by iqraquran** [comment]
Same issue did you know any way to update locale?

**Comment by darkmehmet** [comment]
Same issue did you know any way to update locale?

**Comment by darkmehmet** [comment]
I found where is the isuue is. I use `GetMaterialApp` from `Get` package to initialize App.
`GetMaterialApp(
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: context.locale,
        debugShowCheckedModeBanner: false,
        initialRoute: '/',
        onGenerateRoute: RouteGenerator.generateRoute,
      ),`

 When I change it to normal one it works.
`MaterialApp(
        localizationsDelegates: context.localizationDelegates,
        supportedLocales: context.supportedLocales,
        locale: context.locale,
        debugShowCheckedModeBanner: false,
        initialRoute: '/',
        onGenerateRoute: RouteGenerator.generateRoute,
      ),`

**Comment by AhmedAbouelkher** [comment]
> I found where is the isuue is. I use `GetMaterialApp` from `Get` package to initialize App.
> `GetMaterialApp( localizationsDelegates: context.localizationDelegates, supportedLocales: context.supportedLocales, locale: context.locale, debugShowCheckedModeBanner: false, initialRoute: '/', onGenerateRoute: RouteGenerator.generateRoute, ),`
> 
> When I change it to normal one it works.
> `MaterialApp( localizationsDelegates: context.localizationDelegates, supportedLocales: context.supportedLocales, locale: context.locale, debugShowCheckedModeBanner: false, initialRoute: '/', onGenerateRoute: RouteGenerator.generateRoute, ),`

This issue here that simply removing `GetMaterialApp ` will be very difficult because literally, the whole app depends on it.

**Comment by AhmedAbouelkher** [comment]
I have found a possible solution.

In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change 

```
final _newLocale = Locale('ar', 'EG')
await context.setLocale(_newLocale); // change `easy_localization` locale
Get.updateLocale(_newLocale); // change `Get` locale direction
```

**Comment by darkmehmet** [comment]
> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```

It worked thanks 👏

**Comment by red-star25** [comment]
> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```

Okay @AhmedAbouelkher Thanks for the Solution. It's working now 👍
I'm closing the issue now..

**Comment by MiranKm** [comment]
> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```

What if you aren't using Get? 
I still have this problem!

**Comment by JaviCore** [comment]
Same issue here with 2.3.3 (can't use 3.0 due to not supporting flutter 2.0 in the current app) and not using Get.
Need to actually hot reload the app for changes to actually take place, if not the font size weirdly changes but not the language.

**Comment by JaviCore** [comment]
Just posting again to say that this actually works: https://stackoverflow.com/questions/43778488/how-to-force-flutter-to-rebuild-redraw-all-widgets

```
@override
Widget build(BuildContext context) { 
  rebuildAllChildren(context);
  return MaterialApp( ....
}

void rebuildAllChildren(BuildContext context) {
  void rebuild(Element el) {
    el.markNeedsBuild();
    el.visitChildren(rebuild);
  }
  (context as Element).visitChildren(rebuild);
}
```

It was posted by the author of the i18n_extension ( https://pub.dev/packages/i18n_extension ) and even though it shouldn't be recommended it seems to be the only way to inmediately refresh the widget tree to show the new locale properly.

**Comment by alhoqbani** [comment]
I had the same problem, becuase I was missing `locale: context.locale,` in `MaterialApp`

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: MyHomePage()
    );
  }
}

```

**Comment by markfili** [comment]
our app is not using Get, it has `locale: context.locale` set and still the language changes only if the whole screen is redrawn (ie. closed and opened again) - any other widget that's visible or was created before the language change doesn't change its content to match selected language.

using a DropdownButton to set locale
```
  onChanged: (value) async {
    if (value != null) {
      await context.setLocale(value);
    }
  },
```
example of 2 locale changes, one after the other

```
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
I/flutter (19778): [🌎 Easy Localization] [INFO] Locale de changed
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Build
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init provider
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load Localization Delegate
I/flutter (19778): [🌎 Easy Localization] [INFO] Locale de saved
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
I/flutter (19778): [🌎 Easy Localization] [INFO] Locale en changed
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Build
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init provider
I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load Localization Delegate
I/flutter (19778): [🌎 Easy Localization] [INFO] Locale en saved
```

**Comment by desmondtayweechuan** [comment]
> our app is not using Get, it has `locale: context.locale` set and still the language changes only if the whole screen is redrawn (ie. closed and opened again) - any other widget that's visible or was created before the language change doesn't change its content to match selected language.
> 
> using a DropdownButton to set locale
> 
> ```
>   onChanged: (value) async {
>     if (value != null) {
>       await context.setLocale(value);
>     }
>   },
> ```
> 
> example of 2 locale changes, one after the other
> 
> ```
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
> I/flutter (19778): [🌎 Easy Localization] [INFO] Locale de changed
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Build
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init provider
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load Localization Delegate
> I/flutter (19778): [🌎 Easy Localization] [INFO] Locale de saved
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations
> I/flutter (19778): [🌎 Easy Localization] [INFO] Locale en changed
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Build
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init Localization Delegate
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Init provider
> I/flutter (19778): [🌎 Easy Localization] [DEBUG] Load Localization Delegate
> I/flutter (19778): [🌎 Easy Localization] [INFO] Locale en saved
> ```

Could you share you `MaterialApp` widget?

**Comment by Abdelazeem777** [comment]
I tried this solution which allows me to rebuild the whole widget tree by adding a new unique key every time the localization change.

```
return MaterialApp(
      key: UniqueKey(),
```

**Comment by markfili** [comment]
> > our app is not using Get, it has `locale: context.locale` set and still the language changes only if the whole screen is redrawn (ie. closed and opened again) - any other widget that's visible or was created before the language change doesn't change....
> 
> Could you share you `MaterialApp` widget?

Here you go:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  runApp(
    EasyLocalization(
      supportedLocales: [Locale('en'), Locale('de')],
      path: 'assets/translations',
      fallbackLocale: Locale('en'),
      child: App(),
    ),
  );
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: MainScreen(),
    );
  }
}
```

**Comment by markfili** [comment]
> I tried this solution which allows me to rebuild the whole widget tree by adding a new unique key every time the localization change.
> 
> ```
> return MaterialApp(
>       key: UniqueKey(),
> ```

this really feels like too much to do to in Flutter whose performance is based on redrawing only necessary views...

**Comment by markfili** [comment]
I was trying to debug the problem and it suddenly worked when I added a `print()` command in the build method:
![image](https://user-images.githubusercontent.com/3738182/121882341-b41e7d80-cd10-11eb-8d06-7818166f0e54.png)

not really sure how useful is that but there it is, maybe someone can recognise the problem...

**Comment by uzumaki258** [comment]
> > I have found a possible solution.
> > In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> > ```
> > final _newLocale = Locale('ar', 'EG')
> > await context.setLocale(_newLocale); // change `easy_localization` locale
> > Get.updateLocale(_newLocale); // change `Get` locale direction
> > ```
> 
> Okay @AhmedAbouelkher Thanks for the Solution. It's working now 👍
> I'm closing the issue now..

I have used it. But still sometime not working.

**Comment by Abdulazeez-Raja** [comment]
`if (newValue == LocaleKeys.arabic.tr()) {
                        this.setState(() {
                          dropdownValue = LocaleKeys.arabic.tr();

                          context.setLocale(Locale('ar'));
                        });`

**Comment by markfili** [comment]
> `if (newValue == LocaleKeys.arabic.tr()) {
> this.setState(() {
> dropdownValue = LocaleKeys.arabic.tr();
> 
> ```
>                       context.setLocale(Locale('ar'));
>                     });`
> ```

no, that does nothing...

**Comment by Abdulazeez-Raja** [comment]
> > `if (newValue == LocaleKeys.arabic.tr()) {
> 
> > this.setState(() {
> 
> > dropdownValue = LocaleKeys.arabic.tr();
> 
> > 
> 
> > ```
> 
> >                       context.setLocale(Locale('ar'));
> 
> >                     });`
> 
> > ```
> 
> 
> 
> no, that does nothing...

it's work with me

**Comment by markfili** [comment]
yeah, thank you, your comment made me think and it seems that in my case it doesn't work (doesn't rebuild the screen on which the dropdown is) because the dropdown button and `setLocale` are located several widgets away from the content that should change language but didn't.

I will now implement some kind of listener or move the whole `setLocale` logic up the tree and use `setState` to force a refresh.

**Comment by nullbytesoftware** [comment]
Why is this closed?

**Comment by azazadev** [comment]
same issue here, Why is this closed ?

**Comment by naamapps** [comment]
Same issue, only some widgets are rebuilding, but most of the app stays in the old selected language.

**Comment by ebo8** [comment]
Having the same issue.

**Comment by khaledeltarabily** [comment]
Having the same issue.

**Comment by nullbytesoftware** [comment]
I managed to solve it by rebuilding my `MaterialApp` whenever the language change. The following is my bloc implementation:

```
BlocBuilder<LocalizaitionCubit,LocalizaitionState>(
          buildWhen: (state, newState) =>
              newState is LocalizationLanguageUpdatedState && newState.current.languageCode != context.locale.languageCode,
          builder: (context, state) {
                        return MaterialApp.router(
                           key: ValueKey('${context.locale}'),
                        .......)
```

**Comment by naamapps** [comment]
@nullbytesoftware I read somewhere that it is not recommended.
Does it rebuild everything or restarts the app completely?

**Comment by nullbytesoftware** [comment]
> @nullbytesoftware I read somewhere that it is not recommended.
> Does it rebuild everything or restarts the app completely?

Yes it does rebuild the whole app. I have my providers & dependences above ‘MaterialApp’ so it doesn’t matter for my use case.

**Comment by naamapps** [comment]
@nullbytesoftware cool I'll try it out. But I think this package should do it internally tho.

**Comment by ebo8** [comment]
As a band aid solution, the following seems to work:
```
Widget build(BuildContext context) {
    context.locale; // add this line
```

**Comment by YomiCasual** [comment]
I don't know if this might help for people that are not using Get. The issue is the way flutter tries to rebuild widgets. Taking a look at the flutter hot reload article might explain better. Apparently, if you have variables you declared final, they might not get rebuilt. The trick is to use  'get' in replacement of final. 

```
E.g 
final bar = foo; 
to
int get bar => foo; 

```
And also add this to your main.dart
 ```
 void rebuildAllChildren(BuildContext context) {
    void rebuild(Element el) {
      el.markNeedsBuild();
      el.visitChildren(rebuild);
    }

    (context as Element).visitChildren(rebuild);
  }
```

and call rebuildAllChildren  immediately after build context of your MaterialApp


This works for me. I hope it does for you.

**Comment by mdrideout** [comment]
I am also having this issue. The UI is not rebuilding the updated translations. I am using Riverpod for state management with Navigator 2.0 (using the Routemaster package). Here is my `MaterialApp.router()`.

I am using 
```dart
context.setLocale(newLocale);
```

Flutter 2.5.1 with sound null safety.

```dart
void main() async {
  // This is just needed for many things to work.
  WidgetsFlutterBinding.ensureInitialized();

  // Init Easy Localization
  await EasyLocalization.ensureInitialized();

  // Run the main app
  runApp(
    EasyLocalization(
      supportedLocales: const [
        Locale('de', 'DE'),
        Locale('en', 'US'),
        Locale('es', 'ES'),
        Locale('fr', 'FR'),
        Locale('it', 'IT'),
        Locale('ja', 'JP'),
        Locale('ko', 'KR'),
        Locale('pt', 'BR'),
      ],
      path: 'assets/translations',
      saveLocale: true,
      fallbackLocale: const Locale('en', 'US'),
      child: const ProviderScope(
        child: MyApp(),
      ),
    ),
  );
}
```

```dart
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  /// InitState
  @override
  void initState() {
    super.initState();
    var widgetsBinding = WidgetsBinding.instance;
    if (widgetsBinding != null) {
      widgetsBinding.addPostFrameCallback((_) async {
        // Initialize app features
        initAppFeatures(context);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Consumer(builder: (context, watch, child) {
      return FeatureDiscovery(
        child: MaterialApp.router(
          locale: context.locale,
          supportedLocales: context.supportedLocales,
          localizationsDelegates: context.localizationDelegates,
          debugShowCheckedModeBanner: false,
          scaffoldMessengerKey: rootScaffoldMessengerKey,
          title: 'MyApp',
          theme: ConnectTheme.themeData(context),
          routerDelegate: RoutemasterDelegate(
            routesBuilder: (context) {
              // Watch for user state changes to rebuild our RouteMap based on user login state
              RouteMap _routeMap = watch(routeMapProvider);
              return _routeMap;
            },
          ),
          routeInformationParser: RoutemasterParser(),
        ),
      );
    });
  }
}
```

Logs after changing locale
```bash
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Load asset from assets/translations<…>
flutter: \^[[32m[🌎 Easy Localization] [INFO] Locale ja_JP changed<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Build<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init Localization Delegate<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init provider<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Load Localization Delegate<…>
flutter: \^[[32m[🌎 Easy Localization] [INFO] Locale ja_JP saved<…>
```

I can confirm that @nullbytesoftware solution of adding the `key` param connected to `context.locale` did fix this for me. However, as others have mentioned, this seems like a poor solution because only the individual translated widgets should be rebuilding. Specifically, this is rebuilding my routes (**Navigator 2.0**) so the users loses their position within the app when the language changes.
```dart
MaterialApp.router(
          key: ValueKey('${context.locale}'),
```

Other dependencies in case relevant:
```yaml
dependencies:
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  horizontal_data_table: 3.4.2
  routemaster: ^0.10.0-dev2
  collection: ^1.15.0
  artemis: ^7.1.1-beta.1
  logger: ^1.0.0
  flutter_riverpod: ^0.14.0+3
  graphql: ^5.0.0
  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  email_validator: ^2.0.1
  meta: ^1.7.0
  equatable: ^2.0.3
  url_launcher: ^6.0.11
  flutter_markdown: ^0.6.6
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  feature_discovery: ^0.14.0
  flutter_appauth: ^1.1.0
  flutter_appauth_web:
    path: ./custom_packages/flutter_appauth_web
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  easy_localization: ^3.0.0
```

@Overman775 - Any new ideas? I had no issues with 2.3.3+1, but now that I am migrating to null safety, I need 3.0.

**Comment by mdrideout** [comment]
I'd like to note, that the solution I implemented above (https://github.com/aissat/easy_localization/issues/370#issuecomment-927223962) is not working well. The "refresh" sometimes does not change the language.

If I change it again to a third language, it may switch to the second language I tried. After a few changes, it starts working better. It's very odd. I think it could be a file loading issue for larger translation files? Not sure yet.  

**Edit / Update**: I refactored my app to utilize the [Flutter native localization features](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) with Riverpod state management for real-time persistent language changes, which has been much more reliable.

I have an example repo here (where Riverpod manages the language state). This has totally replaced any needs or advantages that easy_localization once provided. https://github.com/mdrideout/Riverpod-Localization

**Comment by ebwood** [comment]
I think the package should add `listen` property in tr() or plural() method to listen locale change every time. Under the hood, it just call the context.locale function to call `context.dependOnInheritedWidgetOfExactType`.

**Comment by obidano** [comment]
> > I have found a possible solution.
> > In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> > ```
> > final _newLocale = Locale('ar', 'EG')
> > await context.setLocale(_newLocale); // change `easy_localization` locale
> > Get.updateLocale(_newLocale); // change `Get` locale direction
> > ```
> 
> It worked thanks 👏



> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```

Work great!!!

**Comment by culunvb** [comment]
I Just Add this cheat on my screen

Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    print(context.locale);

and itworks

easy_localization : ^3.0.0

**Comment by markfili** [comment]
I also went on that "print in the build method" path but that didn't solve the problem when running the app in profile mode and also, it's really a cheat, feels awkward and weird to see that something should work that way. I do see it as a part of the search for a solution, as it seems to me that the print() command delays the return from the build method for just enough time for setLocale to really set the locale... It feels like setLocale takes its time to change the locale and does so after the build method has returned. if that makes sense..

**Comment by rgtstha** [comment]
Any workaround? none of the above solutions worked for me.

**Comment by mapokapo** [comment]
> I think the package should add `listen` property in tr() or plural() method to listen locale change every time. Under the hood, it just call the context.locale function to call `context.dependOnInheritedWidgetOfExactType`.
<br>

I agree. It doesn't make sense that changing the locale only updates the internal value but doesn't trigger a state update. The only solutions I've seen so far are:
1. Using something like [Get](https://pub.dev/packages/get) or [Provider](https://pub.dev/packages/provider) to handle the current locale in your own custom way, thus completely removing the need for `context.locale` and its associated methods, since the value will be tracked in your own custom state anyways. At that point you may as well implement your own localization system like [#370 (@mdrideout)](https://github.com/aissat/easy_localization/issues/370#issuecomment-941895846) suggests.
2. Triggering an app-wide rebuild by doing what [#370 (@ebo8)](https://github.com/aissat/easy_localization/issues/370#issuecomment-920807924) did, thus tanking your performance by causing unnecessary rebuilds.

Ideally, the `context.locale` and `tr()` values should be reactive and rebuild the widgets that depend on them.

**Comment by rgtstha** [comment]
I ended up doing without this package. In fact, flutter has very good documentation. I followed the documentation and solve the issue. Here is official [documentation](https://docs.flutter.dev/development/accessibility-and-localization/internationalization) about internationalization and localization in Flutter.

**Comment by hikmawanaz** [comment]
any update on this issue? or maybe how to use this package properly

**Comment by desxz** [comment]
> I Just Add this cheat on my screen
> 
> Widget build(BuildContext context) { Size size = MediaQuery.of(context).size; print(context.locale);
> 
> and itworks
> 
> easy_localization : ^3.0.0

this works to me thx xD

**Comment by feduke-nukem** [comment]
same problem

**Comment by Faaatman** [comment]
This [solution](https://github.com/aissat/easy_localization/issues/448#issuecomment-1060384227) worked for me

**Comment by byazit** [comment]
Found the solution. When you change the language use this:

`
context.setLocale(locale);
Navigator.pushAndRemoveUntil(
                context,
                MaterialPageRoute(builder: (BuildContext context) => Login()),
                ModalRoute.withName('/')
);
`

**Comment by oussamabelabbas** [comment]
For anyone who's still struggling with this problem.
I found a workaround that works for me (at least for now) but I don't know if It may cost some performance issues (in fact I would appreciate an answer to that question)

while I was trying to figure out a solution I found out that some of my widgets are rebuilt when changing the langue while others are not. so the question became why these widgets are being rebuilt instead of why those are not being rebuilt...

The short answer is `context`.

The only widgets that are rebuilt in my app and their language are changed are widgets that are depending on context.

here's an example of what I mean.

This is the code of a text widget that was being rebuilt and language being changed normally
`Text("best_sellings".tr(), style: Theme.of(context).textTheme.headlineSmall),`

and this is the widget that weren't changing at all ( until I hot reload )
`ElevatedButton.icon(`
`label: Text("explore_all_products".tr(), overflow: TextOverflow.ellipsis),`
`icon: const Icon(Icons.manage_search_rounded),`
`onPressed: () => context.router.push(const ExploreScreenRoute()),`
`),`

the solution that made the button being forced to rebuild after language change is adding this line to the ElevatedButton
`style: Theme.of(context).elevatedButtonTheme.style,`

Again, I don't know if this is costly in performancee but it's doing the job for now.
I am not sure this will work when changing between two languages that have the same directionality.
my case is between arabic(ar) and english(en)

**Comment by FelixMittermeier** [comment]
All of the solutions provided above somehow did not work for me and I wasted a whole night for this but I think I found a fix for it finally. In the end it is surprisingly simple but you have to know it - like nearly every time.

For some reasons (which are not obvious to me) the `MaterialApp` widget somehow keeps its state even if the top level widget gets rebuild. That is the difference to `GetMaterialApp` what is the reason while there are some solutions for it above. I am using GetX but only some features and therefore still have the default `MaterialApp` in my widget tree.

Long story short: add `key: UniqueKey()` to your `MaterialApp`. Then calling `context.setLocale()` also leads to a complete rebuild of the `MaterialApp` widget and now the new locale is applied.

Maybe it helps someone out there who also struggled with this issue for hours :-)

**Comment by alvindrakes** [comment]
> All of the solutions provided above somehow did not work for me and I wasted a whole night for this but I think I found a fix for it finally. In the end it is surprisingly simple but you have to know it - like nearly every time.
> 
> For some reasons (which are not obvious to me) the `MaterialApp` widget somehow keeps its state even if the top level widget gets rebuild. That is the difference to `GetMaterialApp` what is the reason while there are some solutions for it above. I am using GetX but only some features and therefore still have the default `MaterialApp` in my widget tree.
> 
> Long story short: add `key: UniqueKey()` to your `MaterialApp`. Then calling `context.setLocale()` also leads to a complete rebuild of the `MaterialApp` widget and now the new locale is applied.
> 
> Maybe it helps someone out there who also struggled with this issue for hours :-)

@FelixMittermeier Your solutions works but if the app is wrapped inside `GetMaterialApp`. This soulution will restart the app instantly, which might not be ideal.

**Comment by mrgzi** [comment]
I solved this issue with push the same route and remove other routes after setting locale.

```dart
await context.setLocale(Locale('ru'));
await Navigator.pushNamedAndRemoveUntil(context, '/main', (route) => false);
```

**Comment by satyaattili** [comment]
The below workaround works for me

`localeResolutionCallback: (locale, supportedLocales) {
            if (supportedLocales.contains(locale)) {
              context.setLocale(locale!);
              return locale;
            } else {
              context.setLocale(supportedLocales.first);
              return supportedLocales.first;
            }
          },`

The above code need to add for material app, this changes app launguage on ddevice launguage changed.

**Comment by quydn720** [comment]
Hmm, I also have this problem. I have a list view with my custom widget tile, It's only change the widget without the const keyword, I can't get this off. 
example
`
@override
  Widget build(BuildContext context, WidgetRef ref) {
    return ListView(
      children: [
        const ProfileTile(),
        const LanguageTile(),
        const SignOutTile(),
      ],
    );
  }
`

**Comment by quydn720** [comment]
> Hmm, I also have this problem. I have a list view with my custom widget tile, It's only change the widget without the const keyword, I can't get this off. example `@override Widget build(BuildContext context, WidgetRef ref) { return ListView( children: [ const ProfileTile(), const LanguageTile(), const SignOutTile(), ], ); }`

If I remove the const, it will be redrawn and change the text, wonder why

**Comment by mrgzi** [comment]
> > Hmm, I also have this problem. I have a list view with my custom widget tile, It's only change the widget without the const keyword, I can't get this off. example `@override Widget build(BuildContext context, WidgetRef ref) { return ListView( children: [ const ProfileTile(), const LanguageTile(), const SignOutTile(), ], ); }`
> 
> If I remove the const, it will be redrawn and change the text, wonder why

@quydn720 Yes, I was trying to change language in a dialog. When I removed const, it changed. But for some reason, it was setting the previous locale's strings in the dialog, it sets the other widgets on the screen correctly. I solved this using setState.
```dart
    await context.setLocale(Locale('ru'));
    WidgetsBinding.instance!.addPostFrameCallback((_) {
      setState(() {});
    });
```

**Comment by Davywiz** [comment]
I solved this by wrapping MaterialApp with a BlocListener, then calling
listener: (context, state) async {
await context.setLocale(state.locale);
 }

**Comment by saifalyiu7995** [comment]
my texts/Strings are not updating while it is switching to ltr to rtl, but somehow unable to switch texts on screen. I can see the change after hot reload.

**Comment by EhabSalah** [comment]
Any updates according this issue? 

Randomly the layout direction changes but the text translation keep the same! 🤷🏻‍♂️

**Comment by manoj-gslab** [comment]
Getting this error? any idea?

Unhandled Exception: 'package:easy_localization/src/easy_localization_app.dart': Failed assertion: line 216 pos 14: 'parent.supportedLocales.contains(locale)': is not true.

**Comment by thinhlh** [comment]
For me, I was missing `supportedLocales: ctx.supportedLocales` inside MaterialApp setup

**Comment by htetaunglin** [comment]
> Just posting again to say that this actually works: https://stackoverflow.com/questions/43778488/how-to-force-flutter-to-rebuild-redraw-all-widgets
> 
> ```
> @override
> Widget build(BuildContext context) { 
>   rebuildAllChildren(context);
>   return MaterialApp( ....
> }
> 
> void rebuildAllChildren(BuildContext context) {
>   void rebuild(Element el) {
>     el.markNeedsBuild();
>     el.visitChildren(rebuild);
>   }
>   (context as Element).visitChildren(rebuild);
> }
> ```
> 
> It was posted by the author of the i18n_extension ( https://pub.dev/packages/i18n_extension ) and even though it shouldn't be recommended it seems to be the only way to inmediately refresh the widget tree to show the new locale properly.

I'm fine with this solution.

**Comment by mosaabseta** [comment]
> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```
 this one worked for thank you

**Comment by amrahmed242** [comment]
For anyone who is not using `GetX` the solution is basically calling 
```dart
final engine = WidgetsFlutterBinding.ensureInitialized();
engine.performReassemble();
```

and that's what `GetX` basically do when changing locales as @AhmedAbouelkher mentioned above 
![code](https://user-images.githubusercontent.com/31352179/201476777-9ae0872e-4f67-4c76-bbd3-8bcd35246f43.png)

**Comment by rakib205** [comment]
same here. Some texts are not changing. Need to refresh the app for change. Not using Get. Any solution?

**Comment by rakib205** [comment]
> https://stackoverflow.com/questions/43778488/how-to-force-flutter-to-rebuild-redraw-all-widgets

this should be the solution for now.

**Comment by rakib205** [comment]
> For anyone who is not using `GetX` the solution is basically calling
> 
> ```
> final engine = WidgetsFlutterBinding.ensureInitialized();
> engine.performReassemble();
> ```
> 
> and that's what `GetX` basically do when changing locales as @AhmedAbouelkher mentioned above ![code](https://user-images.githubusercontent.com/31352179/201476777-9ae0872e-4f67-4c76-bbd3-8bcd35246f43.png)

This is working for me.

**Comment by MiladAtef** [comment]
> For anyone who is not using `GetX` the solution is basically calling
> 
> ```
> final engine = WidgetsFlutterBinding.ensureInitialized();
> engine.performReassemble();
> ```
> 
> and that's what `GetX` basically do when changing locales as @AhmedAbouelkher mentioned above ![code](https://user-images.githubusercontent.com/31352179/201476777-9ae0872e-4f67-4c76-bbd3-8bcd35246f43.png)

This worked for me , thanks.

**Comment by MoHortus** [comment]
EDIT: ok actually things dont work after second click of the button as they should. It is just that as I am switching between only 2 languages. Everytime after context.setLocale, "tr()" is still using old values of context.locale (or whole context?). So tr() is kind of all the time one step behind...


Similar problem still on 3.0.1.
After the startup value is ok. But then I have a button to switch value to other language. on first click value does not change. But on second and further clicks things work. Tried a few solutions above, nothing works.

In my case for example lets say I have on initialization correct values releated to "firstLocale". Then on first click of the button for language switch I have:
```
context.setLocale(secondLocale);
setState(() {
  message = messageId.tr();
});
```

Then if i go in debug mode and stop right after the last line of code, I check:
`context.locale`
which is "secondLocale".
However, when I use
`messageId.tr()`
tr() returns translation for the firstLocale... So somehow tr() does not know yet of the update of context.locale...

But if I click on the button again, then things start to work...

**Comment by MoHortus** [comment]
OK, to make things work for me I downloaded the package for version 3.0.1, added it to the project locally and slightly changed `easy_localization_controller.dart`.
Note: yes I have no idea if this is correct approach and did not test what would happen when having big json files. So any comment on that is very welcome.

So in `easy_localization_controller.dart` I added `Localization.load` to `loadTranslations()`. For `Localization.load`, I also had to add to the top `import 'localization.dart'`. So the whole `loadTranslations()` looks like this:

```
  Future loadTranslations() async {
    Map<String, dynamic> data;
    try {
      data = await loadTranslationData(_locale);
      _translations = Translations(data);

      // Added Localization.load. Also needed to add "import 'localization.dart'" at the top.
      Localization.load(_locale,translations:_translations);

      if (useFallbackTranslations && _fallbackLocale != null) {
        data = await loadTranslationData(_fallbackLocale!);
        _fallbackTranslations = Translations(data);

        // also added as the part of the fix. Did not test this, but I presume it should be here.
        Localization.load(_fallbackLocale!,fallbackTranslations:_fallbackTranslations);

      }
    } on FlutterError catch (e) {
      onLoadError(e);
    } catch (e) {
      onLoadError(FlutterError(e.toString()));
    }
  }
```

Then in my `main.dart` I have function to change language, which also have to have async. So part of the code which takes care for the language switch would be:
```
      await context.setLocale(changeToLocale);
      setState(() {
        message = messageId.tr();
      });
```

So now finally, `tr()` gets the right translation as assigned by the `setLocale` two lines before. Without the fix as mention above, it lags one step behind.

**Comment by AmineZeroual** [comment]
if you are using GetMaterialApp you have 2 solutions that worked for me :
1 :
Add key in GetMaterialApp as UniquKey();
GetMaterialApp(
              key: UniqueKey(),
              useInheritedMediaQuery: true,
              locale:context.locale,
              localizationsDelegates: context.localizationDelegates,
              supportedLocales: context.supportedLocales,

and it should work but it will rebuild the app tree.
2 : 
After setting the Locale you need to update the Get Local like this ;
 await context.setLocale(const Locale("en"));
 Get.updateLocale( const Locale("en"));
and this will keep you on the same screen and update Locale over all the app

**Comment by aissat** [comment]
Duplicate of #448 #552

**Comment by ViktorKirjanov** [comment]
the only solution i found is to add context.setLocale(context.locale) in the  beginning of build method if you widget does not want to change the locale

```
...
@override
  Widget build(BuildContext context) {
    context.setLocale(context.locale);
    return ...
```

**Comment by dimashimko** [comment]
I solved it when wrapped the BottomNavigationBar to Localizations.override
`              bottomNavigationBar: Localizations.override(`
`                context: context,`
`                locale: context.locale,`
`                child: CustomBottomNavigationBar(`
`                ),`
`              ),`
It is also important that the elements are inside build method... for example: 
`  Widget build(BuildContext context) {`
  `  List<_BottomNavigationBarItem> items = [`
  `    _BottomNavigationBarItem(`
  `      iconSelectedPath: AppIcons.report_dark,`
  `      iconNoSelectedPath: AppIcons.report_white,`
  `      title: LocaleKeys.report.tr(),`
  `    ),`
  `    _BottomNavigationBarItem(`
  `      iconSelectedPath: AppIcons.home_dark,`
  `      iconNoSelectedPath: AppIcons.home_white,`
  `      title: LocaleKeys.home.tr(),`
  `    ),`
  `    _BottomNavigationBarItem(`
  `      iconSelectedPath: AppIcons.settings_dark,`
  `      iconNoSelectedPath: AppIcons.settings_white,`
  `      title: LocaleKeys.settings.tr(),`
  `    ),`
  `  ];`
 `   ...`
`  }`

**Comment by ptiszai** [comment]
Solved.
Using a DropdownButton to set locale

  onChanged: (value) async {
    if (value != null) {
      await context.setLocale(value);
       setState(() {});  // very importend
    }
  },

**Comment by ptiszai** [comment]
using a DropdownButton to set locale

  onChanged: (value) async {
    if (value != null) {
      await context.setLocale(value);
 setState(() {});
    }
  },

**Comment by AmarchandK** [comment]
> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```

it works man

**Comment by abasu0713** [comment]
For people coming back to this problem.. You wouldn't believe the fix is so easy. I had the exact same problem.

Simply do this:

`onChanged: (value) async {
                  await context.setLocale(Locale.fromSubtags(languageCode: value!.languageCode, countryCode: value.countryCode));
                  setState((){});
}`

Remember to call the set state after the setLocale finishes. It's of type `Future<void>` and you need to wait. And call setState() after it finishes.

**Comment by abasu0713** [comment]
> > I have found a possible solution.
> > In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> > ```
> > final _newLocale = Locale('ar', 'EG')
> > await context.setLocale(_newLocale); // change `easy_localization` locale
> > Get.updateLocale(_newLocale); // change `Get` locale direction
> > ```
> 
> it works man

Upvoting because of your async answer!

**Comment by yagizdo** [comment]
I am currently using Easy Localization 3.0.1 . I tried most of the above solutions.

The method of deleting Const worked for me, but I didn't use it because deleting it throughout the entire application could cause issues. The approach of adding UniqueKey() to MaterialApp also worked, but I didn't like it because it refreshed the entire app as if it had crashed.

But the engine method at the bottom works flawlessly for now. Thank you!

> For anyone who is not using `GetX` the solution is basically calling
> 
> ```
> final engine = WidgetsFlutterBinding.ensureInitialized();
> engine.performReassemble();
> ```
> 
> and that's what `GetX` basically do when changing locales as @AhmedAbouelkher mentioned above ![code](https://user-images.githubusercontent.com/31352179/201476777-9ae0872e-4f67-4c76-bbd3-8bcd35246f43.png)

**Comment by markfili** [comment]
> ... the engine method at the bottom works flawlessly for now.

Calling `performReassemble`
```
await context.setLocale(locale);
await WidgetsBinding.instance.performReassemble();
```
works, but at what cost? It says it rebuilds the whole application which is not a big deal if you're 2 screens in but if you're 50 screens away and you change your language from, let's say, a drawer, what could happen?

**Comment by yagizdo** [comment]
> > ... the engine method at the bottom works flawlessly for now.
> 
> Calling `performReassemble`
> 
> ```
> await context.setLocale(locale);
> await WidgetsBinding.instance.performReassemble();
> ```
> 
> works, but at what cost? It says it rebuilds the whole application which is not a big deal if you're 2 screens in but if you're 50 screens away and you change your language from, let's say, a drawer, what could happen?

I agree with what you said, but this solution worked best among the ones I tried.

**Comment by amrahmed242** [comment]
> > ... the engine method at the bottom works flawlessly for now.
> 
> Calling `performReassemble`
> 
> ```
> await context.setLocale(locale);
> await WidgetsBinding.instance.performReassemble();
> ```
> 
> works, but at what cost? It says it rebuilds the whole application which is not a big deal if you're 2 screens in but if you're 50 screens away and you change your language from, let's say, a drawer, what could happen?

Ideally speaking this would not be good if you navigated 50 routes, practically i can't see a real case scenario were that 
 can happen.

**Comment by Frankdroid7** [comment]
> I have found a possible solution.
> 
> In case you are using `GetMaterialApp` you should when changing the current language call ` Get.updateLocale()` to inform `GetMaterialApp` about the language change
> 
> ```
> final _newLocale = Locale('ar', 'EG')
> await context.setLocale(_newLocale); // change `easy_localization` locale
> Get.updateLocale(_newLocale); // change `Get` locale direction
> ```

Thanks alot, this worked!

**Comment by SamedHrmn** [comment]
Hi, Is there any update for handle rebuilding internally after setLocale? The solutions I've read about don't seem to be suitable for production applications, and I don't want to use any third-party packages either.

**Comment by Miguel-A-Jara** [comment]
Well... after trying many things out. I finally found a solution:

### Use:
```
final myTranslatedHelloWorld = context.tr("my_awesome_key");
```

### Instead of any of these
```
final myTranslatedHelloWorld = "my_awesome_key".tr();
final myTranslatedHelloWorld = tr("my_awesome_key");
final myTranslatedHelloWorld = Text("my_awesome_key").tr();
```

**_Or..._**

### Pass context to your tr() functions.
```
final myTranslatedHelloWorld = "my_awesome_key".tr(context: context);
final myTranslatedHelloWorld = tr("my_awesome_key", context: context);
final myTranslatedHelloWorld = Text("my_awesome_key").tr(context: context);
```

**Comment by ongyul** [comment]
> This [solution](https://github.com/aissat/easy_localization/issues/448#issuecomment-1060384227) worked for me

it is perfect

**Comment by IbrahimAlqayyas** [comment]
> > ... the engine method at the bottom works flawlessly for now.
> 
> Calling `performReassemble`
> 
> ```
> await context.setLocale(locale);
> await WidgetsBinding.instance.performReassemble();
> ```
> 
> works, but at what cost? It says it rebuilds the whole application which is not a big deal if you're 2 screens in but if you're 50 screens away and you change your language from, let's say, a drawer, what could happen?

Thank you, I was stuck for 3 months with this problem and thanks Allah he caused you to solve my problem.

**Comment by Muhammed-Ayad** [comment]
> I solved it when wrapped the BottomNavigationBar to Localizations.override ` bottomNavigationBar: Localizations.override(` ` context: context,` ` locale: context.locale,` ` child: CustomBottomNavigationBar(` ` ),` ` ),` It is also important that the elements are inside build method... for example: ` Widget build(BuildContext context) {` ` List<_BottomNavigationBarItem> items = [` ` _BottomNavigationBarItem(` ` iconSelectedPath: AppIcons.report_dark,` ` iconNoSelectedPath: AppIcons.report_white,` ` title: LocaleKeys.report.tr(),` ` ),` ` _BottomNavigationBarItem(` ` iconSelectedPath: AppIcons.home_dark,` ` iconNoSelectedPath: AppIcons.home_white,` ` title: LocaleKeys.home.tr(),` ` ),` ` _BottomNavigationBarItem(` ` iconSelectedPath: AppIcons.settings_dark,` ` iconNoSelectedPath: AppIcons.settings_white,` ` title: LocaleKeys.settings.tr(),` ` ),` ` ];` ` ...` ` }`

it is perfect

**Comment by MohamedSalama0** [comment]
> For anyone who is not using `GetX` the solution is basically calling
> 
> ```dart
> final engine = WidgetsFlutterBinding.ensureInitialized();
> engine.performReassemble();
> ```
> 
> and that's what `GetX` basically do when changing locales as @AhmedAbouelkher mentioned above ![code](https://user-images.githubusercontent.com/31352179/201476777-9ae0872e-4f67-4c76-bbd3-8bcd35246f43.png)

this worked for me too, But is that can effect on app's performance ?

**Comment by shihabkandil** [comment]
when using the translated keys like this ``` LocaleKeys.login.tr()``` the widgets dont get the update of context.locale and delegates change but if you linked the translations widgets with context like this ``` context.tr(LocaleKeys.login) ``` then it will work ...
what I found later that even 1 usage of  any translation using context like ``` context.tr(LocaleKeys.login) ``` in a screen is able to update all other translations even if they were written in that way without context``` LocaleKeys.login.tr()```

**Comment by MoatazNoaman2001** [comment]
> For anyone who is not using `GetX` the solution is basically calling 
> ```dart
> final engine = WidgetsFlutterBinding.ensureInitialized();
> engine.performReassemble();
> ```
> 
> and that's what `GetX` basically do when changing locales as @AhmedAbouelkher mentioned above 
> ![code](https://user-images.githubusercontent.com/31352179/201476777-9ae0872e-4f67-4c76-bbd3-8bcd35246f43.png)
> 

I done this but unfortunately no thing is changed

**Comment by oguzarapkirli** [comment]
> ```dart
>     locale: context.locale,
> ```

Damn i feel really dumb rn. Thanks it's worked for me i just forgot to use context

**Comment by lovenangelo** [comment]
https://stackoverflow.com/questions/78921888/ui-not-updated-when-changing-locale-easy-localization

This one helped me, just passing context to the LocaleKeys generated class does the trick
